///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assets1 = 'assets/1.png';
  static const String assetsCarbon = 'assets/carbon (1).png';

  /// Audios
  static const String audios1 = 'assets/audios/1.mp3';
  static const String audios2 = 'assets/audios/2.mp3';
  static const String audios3 = 'assets/audios/3.mp3';
  static const String audios4 = 'assets/audios/4.mp3';
  static const String audios5 = 'assets/audios/5.mp3';
  static const String audios6 = 'assets/audios/6.mp3';
  static const String audios7 = 'assets/audios/7.mp3';
  static const String audios8 = 'assets/audios/8.mp3';
  static const String audios9 = 'assets/audios/9.mp3';
  static const String audios10 = 'assets/audios/10.mp3';
  static const String audios11 = 'assets/audios/11.mp3';
  static const String audios12 = 'assets/audios/12.mp3';
  static const String audios13 = 'assets/audios/13.mp3';
  static const String audios14 = 'assets/audios/14.mp3';
  static const String shaykh = "الشيخ مزمل فقيري حفظه الله";

}
